insert into dnsadmin_recordtype (name,description) values ('A','IPv4 Address Record');
insert into dnsadmin_recordtype (name,description) values ('NS','Name Server Record');
insert into dnsadmin_recordtype (name,description) values ('PTR','Pointer Record');
insert into dnsadmin_recordtype (name,description) values ('SOA','Start of Authority Record');
insert into dnsadmin_recordtype (name,description) values ('TXT','Text Record');
insert into dnsadmin_recordtype (name,description) values ('CNAME','Host Alias Record');
insert into dnsadmin_recordtype (name,description) values ('MX','Mail Exchanger Record');
insert into dnsadmin_recordtype (name,description) values ('SRV','Services Record');
insert into dnsadmin_recordtype (name,description) values ('A6','IPv6 Address Record');
insert into dnsadmin_recordtype (name,description) values ('DNAME','Delegate Reverse Name Record');
insert into dnsadmin_recordtype (name,description) values ('HINFO','System Information Record');
insert into dnsadmin_recordtype (name,description) values ('KEY','DNSSEC Public Key Record');
insert into dnsadmin_recordtype (name,description) values ('NXT','DNSSEC Content Record');
insert into dnsadmin_recordtype (name,description) values ('SIG','DNSSEC Signature Record');
